version: 2
jobs:
  build_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints: bb:a9:31:51:33:1e:3b:bc:d1:d2:9b:f6:67:36:b9:27
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "package.json" }}
      - run: git config user.name $GH_USER
      - run: npm run build:gh-pages
      - run: npm run generate:gh-pages
      - run: npm run deploy
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: source